-- V2: modelo real de usuario (maestro) y usuario_rol (detalle).
-- Aplicar manualmente en bases existentes. En instalaciones nuevas Docker lo aplica al inicializar.
CREATE TABLE IF NOT EXISTS rol (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre VARCHAR(80) NOT NULL UNIQUE,
 activo BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS usuario (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 correo VARCHAR(254) NOT NULL UNIQUE,
 password_hash TEXT NOT NULL,
 activo BOOLEAN NOT NULL DEFAULT TRUE,
 CONSTRAINT ck_usuario_correo CHECK (length(trim(correo)) > 3)
);
CREATE TABLE IF NOT EXISTS usuario_rol (
 usuario_id BIGINT NOT NULL REFERENCES usuario(id),
 rol_id INTEGER NOT NULL REFERENCES rol(id),
 PRIMARY KEY(usuario_id,rol_id)
);
INSERT INTO rol(nombre) VALUES ('Administrador'),('Investigador'),('Coordinador')
ON CONFLICT (nombre) DO NOTHING;

-- FK del detalle siempre validada en PostgreSQL; no basta con un select del frontend.
CREATE OR REPLACE VIEW vw_usuarios_roles AS
 SELECT u.id, u.correo, u.activo,
 COALESCE(jsonb_agg(jsonb_build_object('id',r.id,'nombre',r.nombre))
 FILTER (WHERE r.id IS NOT NULL),'[]'::jsonb) AS roles
 FROM usuario u LEFT JOIN usuario_rol ur ON ur.usuario_id=u.id
 LEFT JOIN rol r ON r.id=ur.rol_id
 GROUP BY u.id,u.correo,u.activo;

CREATE OR REPLACE FUNCTION fn_usuario_crear(p_correo TEXT,p_hash TEXT,p_roles JSONB)
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE v_id BIGINT; v_total INT;
BEGIN
 IF p_correo IS NULL OR position('@' in p_correo)=0 OR p_hash IS NULL OR length(p_hash)<50 THEN
   RAISE EXCEPTION 'Datos del usuario invalidos' USING ERRCODE='22023';
 END IF;
 IF p_roles IS NULL OR jsonb_typeof(p_roles)<>'array' OR jsonb_array_length(p_roles)=0 THEN
   RAISE EXCEPTION 'Se requiere un arreglo no vacio de roles' USING ERRCODE='22023';
 END IF;
 SELECT count(DISTINCT value::int) INTO v_total FROM jsonb_array_elements_text(p_roles);
 IF v_total <> (SELECT count(*) FROM rol WHERE activo AND id IN (SELECT value::int FROM jsonb_array_elements_text(p_roles))) THEN
   RAISE EXCEPTION 'Roles inexistentes o inactivos' USING ERRCODE='23503';
 END IF;
 INSERT INTO usuario(correo,password_hash) VALUES(lower(trim(p_correo)),p_hash) RETURNING id INTO v_id;
 INSERT INTO usuario_rol(usuario_id,rol_id) SELECT v_id, DISTINCT_ROLES.rol_id
 FROM (SELECT DISTINCT value::int AS rol_id FROM jsonb_array_elements_text(p_roles)) DISTINCT_ROLES;
 RETURN fn_usuario_consultar(v_id);
END $$;

CREATE OR REPLACE FUNCTION fn_usuario_consultar(p_id BIGINT)
RETURNS JSONB LANGUAGE sql STABLE AS $$
 SELECT to_jsonb(v) FROM vw_usuarios_roles v WHERE v.id=p_id
$$;
CREATE OR REPLACE FUNCTION fn_usuario_listar()
RETURNS JSONB LANGUAGE sql STABLE AS $$
 SELECT COALESCE(jsonb_agg(to_jsonb(v) ORDER BY v.id),'[]'::jsonb) FROM vw_usuarios_roles v
$$;

CREATE OR REPLACE FUNCTION fn_usuario_actualizar(p_id BIGINT,p_correo TEXT,p_roles JSONB)
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE v_total INT;
BEGIN
 IF p_correo IS NULL OR position('@' in p_correo)=0 OR p_roles IS NULL OR jsonb_typeof(p_roles)<>'array' OR jsonb_array_length(p_roles)=0 THEN
  RAISE EXCEPTION 'Entrada invalida' USING ERRCODE='22023';
 END IF;
 SELECT count(DISTINCT value::int) INTO v_total FROM jsonb_array_elements_text(p_roles);
 IF v_total <> (SELECT count(*) FROM rol WHERE activo AND id IN (SELECT value::int FROM jsonb_array_elements_text(p_roles))) THEN
  RAISE EXCEPTION 'Roles invalidos' USING ERRCODE='23503';
 END IF;
 UPDATE usuario SET correo=lower(trim(p_correo)) WHERE id=p_id AND activo;
 IF NOT FOUND THEN RAISE EXCEPTION 'Usuario inexistente o inactivo' USING ERRCODE='P0002'; END IF;
 DELETE FROM usuario_rol WHERE usuario_id=p_id;
 INSERT INTO usuario_rol(usuario_id,rol_id)
 SELECT p_id,roles.rol_id FROM (SELECT DISTINCT value::int rol_id FROM jsonb_array_elements_text(p_roles)) roles;
 RETURN fn_usuario_consultar(p_id);
END $$;

CREATE OR REPLACE FUNCTION fn_usuario_inactivar(p_id BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql AS $$
BEGIN
 UPDATE usuario SET activo=FALSE WHERE id=p_id AND activo=TRUE;
 RETURN FOUND;
END $$;
